### ISSUE TITLE
Convention map is not rendered

### ISSUE THREAD

**Issue by Stvad** [andreaskasper/scoringCE#3]
When I go to a dancer profile (https://scoring.dance/enUS/wsdc/registry/21627.html) I can see pins rendered over empty space. 
I've tried Chrome/Firefox and opening the tab in incognito mode

![image](https://github.com/andreaskasper/scoringCE/assets/81347/258b6bfd-6d7b-432b-bb7e-f2a27122c4f7)

**Comment by andreaskasper** [comment]
Solved.
The rendermap was not providing the tiles anymore. Switched to a new renderer.

Thanks for the info :-)
