### ISSUE TITLE
Points are not updated correctly for registration

### ISSUE THREAD

**Issue by jblossey** [andreaskasper/scoringCE#4]
## Bug Summary

**Description:**  

I recently got more points which made me eligible to register for intermediate. The wsdc points registry has them online, my profile on scoring.dance is accurate, but when i tried to register for comps at my next event, it showed me my old point count and didn't let me register for the new division.

## Steps to Reproduce

1. Get new point score that let's you transition to new division
2. see whether the points are updated on scoring.dance
3. try to register for a comps at a subsequent event in the new division

## Expected and Actual Results

**Expected Result:**  

The points should be accurately displayed with the latest point count and the new division should be unlocked for registration.

**Actual Result:**  

The point count from before the last event was displayed and i still could only register in novice.

## Reproducibility and Frequency

**Reproducibility:**  
- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable to reproduce

**Frequency:**  

n/a

## Environment Details

**Environment:**  
- **OS:** EndeavourOS Linux x86_64
- **Kernel:** 6.9.3-arch1-1
- **Browser:** Vivaldi
- **Version:** 6.7.3329.39 (Stable channel) stable (64-bit) 
- **Revision:** 7c9e8453c3bda0c609414dae4ca10a7f485af8d7 
- **Configuration Details:**  
  JavaScript	V8 12.4.254.20
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Command Line	/usr/bin/vivaldi-stable --flag-switches-begin --flag-switches-end --save-page-as-mhtml

## Impact and Severity

**Impact on User:**  

Would have to register at the registration desk but i guess their system accesses the same core as the webUI does, so they also might not be able to register me.

## Technical Details

**User Account:**  

WSDC-ID: 22244

**Browser Console Output:** 

cdn.webpushr.com/app.min.js:1 
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
 main.js loaded
register:716 goto page 1
register:950 988L false
register:950 988F false
register:950 989L false
register:950 989F false
register:950 990L true
register:950 990F true
register:950 991L true
register:950 991F true
register:950 992L true
register:950 992F true
register:950 993L false
register:950 993F false
register:950 994L false
register:950 994F false
register:950 995L false
register:950 996L false
register:950 997L false
register:950 998L false
register:950 999L false
register:950 1000L false
register:950 1001L false
register:950 1001F false
register:950 1002L false
register:955 rerendered
register:1 Third-party cookie will be blocked. Learn more in the Issues tab.
Error with Permissions-Policy header: Unrecognized feature: 'battery'.
Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
Error with Permissions-Policy header: Unrecognized feature: 'usb-unrestricted'.
register:670 doaction importdancerjson S.fn.init
register:695 accept Person Object
register:716 goto page 2
register:1007 WSDC data loaded Object
register:950 988L true
register:950 988F false
register:950 989L false
register:950 989F false
register:950 990L true
register:950 990F true
register:950 991L true
register:950 991F true
register:950 992L true
register:950 992F true
register:950 993L false
register:950 993F false
register:950 994L false
register:950 994F false
register:950 995L false
register:950 996L false
register:950 997L false
register:950 998L false
register:950 999L false
register:950 1000L false
register:950 1001L false
register:950 1001F false
register:950 1002L false
register:955 rerendered
register:1045 0
register:950 988L true
register:950 988F false
register:950 989L false
register:950 989F false
register:950 990L true
register:950 990F true
register:950 991L true
register:950 991F true
register:950 992L true
register:950 992F true
register:950 993L false
register:950 993F false
register:950 994L false
register:950 994F false
register:950 995L false
register:950 996L false
register:950 997L false
register:950 998L false
register:950 999L false
register:950 1000L false
register:950 1001L false
register:950 1001F false
register:950 1002L false
register:955 rerendered
www.facebook.com/ajax/bz?__a=1&__ccg=EXCELLENT&__dyn=7wKxa13wt8K2WnF0Sw8W5U4e0yoW1DwfG1-wd-4o3Bw5VCwjE3awbG0MU2awgo1EUhwnU1oU1O81u81x82ewnE3fw6iw4vwbS1Lw7Jw7zwde&__hs=19885.BP%3Aplugin_default_pkg.2.0..0.0&__hsi=7379215484927937564&__req=1&__rev=1014123394&__s=%3A%3Alxpv1v&__sp=1&__user=0&dpr=1&jazoest=21046&locale=en_US&lsd=AVpcxJGjwKw:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Attachments:**  

![image](https://github.com/andreaskasper/scoringCE/assets/57671651/796b54ef-040f-4398-b177-235aff1bb992)

![image](https://github.com/andreaskasper/scoringCE/assets/57671651/3e21c4ad-44c2-488d-b1fe-a171a0d4d74a)

**Comment by andreaskasper** [comment]
Problem is solved. The Configuration of the event was wrong. It ran the Rule "canNOV" on the Intermediate Jack&Jill.

Thanks for the info.
